# Generated by Django 5.0.6 on 2024-07-13 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_categories_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, null=True)),
                ("slug", models.SlugField(max_length=255, null=True)),
                ("ordering", models.IntegerField(default=0, null=True)),
            ],
            options={
                "ordering": ["ordering"],
            },
        ),
        migrations.AddField(
            model_name="categories",
            name="book",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="app.book",
            ),
        ),
    ]
