# Generated by Django 5.0.6 on 2024-07-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_book_categories_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categories",
            name="book",
        ),
        migrations.RemoveField(
            model_name="categories",
            name="slug",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
    ]
