# Generated by Django 5.0.6 on 2024-07-17 14:49

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_categories_book_remove_categories_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Number",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.IntegerField(verbose_name=django.contrib.auth.models.User),
                ),
            ],
        ),
    ]
