# Generated by Django 5.0.6 on 2024-07-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_userprofile_delete_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="last_name",
        ),
    ]
