# Generated by Django 5.0.6 on 2024-07-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_userprofile_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
    ]
