# Generated by Django 5.0.6 on 2024-07-17 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_remove_userprofile_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
